[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.primary]
foreground = "#FFFFFF"
background = "#050707"

[cursor]
style= "Underline"

[window]
opacity = 0.9
padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"
[font]
size = 14.0

[terminal.shell]
program = "/bin/zsh"
