cursor #e6f0ff
cursor_text_color #ffffff

foreground            #e6f0ff
background            #000000
selection_foreground  #c1c1c1
selection_background  #999999
url_color             #974b46

color0   #000000
color1   #ad4747
color2   #579746
color3   #bca74d
color4   #8f3833
color5   #450501
color6   #974b46
color7   #9e9494
color8   #625a5a
color9   #cb7a79
color10  #7fb571
color11  #e2d28d
color12  #a65f5a
color13  #c47f7a
color14  #d3a3a0
color15  #dad5d5
