
# The basic colors
foreground              #F5F0F6
background              #100F0F
selection_foreground    #CECDC3
selection_background    #403E3C

# Cursor colors
cursor                  #CECDC3
cursor_text_color       #100F0F

# kitty window border colors
active_border_color     #AF3029
inactive_border_color   #403E3C

# Tab bar colors
active_tab_foreground   #CECDC3
active_tab_background   #403E3C
inactive_tab_foreground #878580
inactive_tab_background #282726

# The basic 16 colors
# black
color0 #100F0F
color8 #1e1e20

# red
color1 #AF3029
color9 #D14D41

# green
color2  #D4FF00
color10 #879A39

# yellow
color3  #f1e42b
color11 #D0A215

# blue
color4  #1400ea
color12 #4385BE

# magenta
color5  #9c3aca
color13 #CE5D97

# cyan
color6  #85e1b4
color14 #3AA99F

# white
color7  #D1E3DD
color15 #CECDC3

font_size 18
cursor_shape beam
cursor_shape_unfocused hollow
cursor_trail 1
cursor_trail_decay 0.1 0.2
cursor_trail_start_threshold 0
scrollbar never
option_as_alt both

mouse_hide_wait 0.2
url_color #0087bd
url_style curly
open_url_with firefox
detect_urls yes
repaint_delay 0
sync_to_monitor no
input_delay 0

initial_window_width  640
initial_window_height 400
placement_strategy center
confirm_os_window_close 0
window_padding_width 0

# foreground #f1e9d2
# background #000000
background_opacity 0.8

editor nvim
shell /bin/fish

# testing pull2

# BEGIN_KITTY_FONTS
font_family      family='Cascadia Mono NF' style=Light
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
