font_size 18
cursor #FFFFFF
cursor_shape beam
cursor_shape_unfocused hollow
cursor_trail 0
cursor_trail_decay 0.1 0.2
cursor_trail_start_threshold 0
scrollbar never
option_as_alt both

mouse_hide_wait 0.2
url_color #0087bd
url_style curly
open_url_with firefox
detect_urls yes
repaint_delay 0
sync_to_monitor no
input_delay 0

initial_window_width  640
initial_window_height 400
placement_strategy center
confirm_os_window_close 0
window_padding_width 0

foreground #f1e9d2
background #000000
background_opacity 0.9

editor nvim
shell /bin/fish

# testing pull2

# BEGIN_KITTY_FONTS
font_family      family='Cascadia Mono NF' style=Light
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
