[mgr]
show_hidden = true
ratio = [2, 3, 3]
sort_by = "natural"
sort_sensitive = true
sort_dir_first = true
show_symlink = true
scrolloff = 200

[preview]
warp = "yes"
max_width = 2000
max_height = 2000

[opener]
play = [
	{ run = 'mpv "$@"', block = true, for = "unix" },
]
edit = [
	{ run = 'codium "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
img = [
{ run = 'mupdf "$@"', block = false, orphan = true, desc = "Viewer" },
]
dis = [
{ run = 'zathura "$@"', block = false, orphan = true, desc = "Viewer" },
]
office = [
{ run = 'libreoffice "$@"', block = false, orphan = true, desc = "Office" },
]
draw = [
{ run = 'drawio "$@"', block = false, orphan = true, desc = "Draw" },
]
[open]
rules = [
	{ name = "*.drawio", use = "draw" },
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
	{ mime = "music/*", use = "play" },
	{ mime = "image/*", use = "img" },
	{ mime = "application/pdf", use = "dis" },
	{ mime = "application/epub+zip", use = "dis" },
	{ mime = "application/oasis.opendocument.graphics", use = "office" },
	{ mime = "application/oasis.opendocument.text", use = "office" },

	# { mime = "application/json", use = "edit" },
	{ name = "*.json", use = "edit" },
	{ name = "*.toml", use = "edit" },
	{ name = "*.md", use = "edit" },
	{ name = "*.lua", use = "edit" },
	{ name = "*.py", use = "edit" },
	{ name = "*.org", use = "edit" },
	{ name = "*.typ", use = "edit" },

	# Multiple openers for a single rule
	{ name = "*.html", use = "edit" },
]
[plugin]
prepend_previewers = [
	# HEIC previewer
	{ mime = "image/heic", run = "heic" },
	# RAF previewer
	{ name = "*.raf", run = "raf" },
]

append_previewers = [
	# My fallback previewer
	{ name = "*", run = "binary" },
]

[input]
cursor_blink = true
