### Editor Config ###

theme = "blackmetal"

[editor]
line-number = "relative"
scrolloff = 5
mouse = true
default-yank-register = '*'
cursorline = true
completion-timeout = 5
bufferline = "never"
text-width = 68
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = "all"
clipboard-provider = "wayland"
rulers = [0, 70]

[editor.statusline]
left = ["position", "position-percentage","spinner"]
center = ["version-control"]
right = ["diagnostics", "file-name", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.indent-guides]
render = true
character = "┆" # "▏", "╎", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

### Keymaps ###

[keys.normal]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

S-l = "extend_to_line_end"
S-h = "extend_to_line_start"
"A-q" = "@mip:reflow<ret>;"

C-e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.normal.g]
a = "code_action"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[keys.normal.space]
q = ":buffer-close"
A = ":lsp-workspace-command"
Z = ":set gutters.line-numbers.min-width 3"
z = ":set gutters.line-numbers.min-width 37"
tab = ":echo %sh{wc -w %{buffer_name}}"

[keys.insert]
S-tab = "move_parent_node_start"
"A-q" = "@jkmip:reflow<ret>A"

[keys.insert.j]
k = "normal_mode"
