dictionaries = [
    "en_us",
    "en_gb",
    "de",
    "fr",
]
words = [
    "aang",
    "adhd",
    "airbender",
    "ams",
    "artin",
    "astroneer",
    "bayonetta",
    "bioshock",
    "blazkowicz",
    "bremergy",
    "codebook",
    "dlc",
    "drawio",
    "elden",
    "eldenring",
    "elmun",
    "gameplay",
    "geogebra",
    "gwn",
    "hvd",
    "hyprland",
    "irem",
    "jinping",
    "korra",
    "kratos",
    "laxasia",
    "liebert",
    "lvms",
    "lvs",
    "neovim",
    "precharge",
    "rnote",
    "rpg",
    "rustc",
    "sdc",
    "signalis",
    "skyrim",
    "soulsborne",
    "speedrun",
    "taskwarrior",
    "tenzen",
    "terria",
    "todo",
    "tsac",
    "tsal",
    "valheim",
    "whatsapp",
    "witcher",
    "wolfenstein",
    "zathura",
    "zellij",
    "zuko",
]
flag_words = [
    "todo",
    "fixme",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
]
ignore_patterns = [
    '\b[ATCG]+\b',
    '\d{3}-\d{2}-\d{4}',
    "^[A-Z]{2,}$",
    'https?://[^\s]+',
]
