return {
  -- "nvim-neorg/neorg",
  -- lazy = false,
  -- -- version = "*",
  -- version = false, -- get latest on branch
  -- opts = {
  --   load = {
  --     ["core.defaults"] = {}, -- Loads default behaviour
  --     ["core.concealer"] = { config = { folds = true, icon_preset = "varied" } }, -- Adds pretty icons to your documents
  --     ["core.keybinds"] = {
  --       config = {
  --         neorg_leader = ",",
  --       },
  --     },
  --     ["core.dirman"] = {
  --       config = {
  --         workspaces = {
  --           notes = "~/Vshrd/Vault/Index/notes/",
  --         },
  --         default_workspace = "notes",
  --       },
  --     },
  --   },
  -- },
}
